// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore_Update.Data;

#nullable disable

namespace NetCore_Update.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251101075101_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NetCore_Update.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("ApplicationUserRole")
                        .HasColumnType("bit");

                    b.Property<bool>("BranchRole")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CustomerRole")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HomeRole")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductRole")
                        .HasColumnType("bit");

                    b.Property<bool>("PurchaseOrderLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("PurchaseOrderRole")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivingLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivingRole")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesOrderLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("SalesOrderRole")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShipmentLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentRole")
                        .HasColumnType("bit");

                    b.Property<bool>("StockRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferInLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferInRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOrderLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOrderRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOutLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TransferOutRole")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("VendorLineRole")
                        .HasColumnType("bit");

                    b.Property<bool>("VendorRole")
                        .HasColumnType("bit");

                    b.Property<bool>("WarehouseRole")
                        .HasColumnType("bit");

                    b.Property<bool>("isSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("profilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Branch", b =>
                {
                    b.Property<string>("branchId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isDefaultBranch")
                        .HasColumnType("bit");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("branchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            branchId = "00000000-0000-0000-0000-000000000001",
                            branchName = "Main Branch",
                            city = "Hanoi",
                            country = "VN",
                            createdAt = new DateTime(2025, 11, 1, 7, 51, 0, 853, DateTimeKind.Utc).AddTicks(8390),
                            description = "Default branch",
                            isDefaultBranch = true,
                            province = "HN",
                            street1 = "123 Main St",
                            street2 = ""
                        });
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Customer", b =>
                {
                    b.Property<string>("customerId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("customerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            customerId = "00000000-0000-0000-0000-000000000001",
                            HasChild = "No",
                            city = "Hanoi",
                            country = "VN",
                            createdAt = new DateTime(2025, 11, 1, 7, 51, 0, 853, DateTimeKind.Utc).AddTicks(8573),
                            customerName = "John Customer",
                            description = "Default customer",
                            province = "HN",
                            size = 1,
                            street1 = "34 Customer St",
                            street2 = ""
                        });
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.CustomerLine", b =>
                {
                    b.Property<string>("customerLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("mobilePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("officePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("personalEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("salutation")
                        .HasColumnType("int");

                    b.Property<string>("workEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("customerLineId");

                    b.HasIndex("customerId");

                    b.ToTable("CustomerLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Product", b =>
                {
                    b.Property<string>("productId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("productType")
                        .HasColumnType("int");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("uom")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = "00000000-0000-0000-0000-000000000001",
                            barcode = "893000000001",
                            createdAt = new DateTime(2025, 11, 1, 7, 51, 0, 853, DateTimeKind.Utc).AddTicks(8536),
                            description = "Demo item",
                            productCode = "P-001",
                            productName = "Sample Product 1",
                            productType = 3,
                            serialNumber = "SN-001",
                            uom = 1
                        },
                        new
                        {
                            productId = "00000000-0000-0000-0000-000000000002",
                            barcode = "893000000002",
                            createdAt = new DateTime(2025, 11, 1, 7, 51, 0, 853, DateTimeKind.Utc).AddTicks(8539),
                            description = "Demo item",
                            productCode = "P-002",
                            productName = "Sample Product 2",
                            productType = 2,
                            serialNumber = "SN-002",
                            uom = 7
                        });
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.PurchaseOrder", b =>
                {
                    b.Property<string>("purchaseOrderId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("deliveryAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("picVendor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("poDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("purchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("purchaseOrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("purchaseReceiveNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenceNumberExternal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("referenceNumberInternal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("top")
                        .HasColumnType("int");

                    b.Property<decimal>("totalDiscountAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("totalOrderAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("purchaseOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("vendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.Property<string>("purchaseOrderLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discountAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("purchaseOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<decimal>("totalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("purchaseOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("purchaseOrderId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Receiving", b =>
                {
                    b.Property<string>("receivingId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("purchaseOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("receivingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("receivingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("vendorDO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("vendorInvoice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("receivingId");

                    b.HasIndex("branchId");

                    b.HasIndex("purchaseOrderId");

                    b.HasIndex("vendorId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Receivings");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.ReceivingLine", b =>
                {
                    b.Property<string>("receivingLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<float>("qtyReceive")
                        .HasColumnType("real");

                    b.Property<string>("receivingId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("receivingId1")
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("receivingLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("receivingId");

                    b.HasIndex("receivingId1");

                    b.HasIndex("warehouseId");

                    b.ToTable("ReceivingLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.SalesOrder", b =>
                {
                    b.Property<string>("salesOrderId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("deliveryAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("picCustomer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("referenceNumberExternal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("referenceNumberInternal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("salesOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("salesOrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("salesShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("soDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("top")
                        .HasColumnType("int");

                    b.Property<decimal>("totalDiscountAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("totalOrderAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("salesOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.SalesOrderLine", b =>
                {
                    b.Property<string>("salesOrderLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discountAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<string>("salesOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<decimal>("totalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("salesOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("salesOrderId");

                    b.ToTable("SalesOrderLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Shipment", b =>
                {
                    b.Property<string>("shipmentId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("customerPO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("expeditionMode")
                        .HasColumnType("int");

                    b.Property<int>("expeditionType")
                        .HasColumnType("int");

                    b.Property<string>("invoice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("salesOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("shipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("shipmentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("shipmentId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.HasIndex("salesOrderId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.ShipmentLine", b =>
                {
                    b.Property<string>("shipmentLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<float>("qtyShipment")
                        .HasColumnType("real");

                    b.Property<string>("shipmentId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("shipmentId1")
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("shipmentLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("shipmentId");

                    b.HasIndex("shipmentId1");

                    b.HasIndex("warehouseId");

                    b.ToTable("ShipmentLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferIn", b =>
                {
                    b.Property<string>("transferInId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchIdFrom")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchIdTo")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("transferInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transferInNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("warehouseIdFrom")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("warehouseIdTo")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("transferInId");

                    b.HasIndex("branchIdFrom");

                    b.HasIndex("branchIdTo");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseIdFrom");

                    b.HasIndex("warehouseIdTo");

                    b.ToTable("TransferIns");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferInLine", b =>
                {
                    b.Property<string>("transferInLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<string>("transferInId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("transferInLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferInId");

                    b.ToTable("TransferInLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOrder", b =>
                {
                    b.Property<string>("transferOrderId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchIdFrom")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchIdTo")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isIssued")
                        .HasColumnType("bit");

                    b.Property<bool>("isReceived")
                        .HasColumnType("bit");

                    b.Property<string>("picName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("transferOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transferOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("transferOrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("warehouseIdFrom")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("warehouseIdTo")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("transferOrderId");

                    b.HasIndex("branchIdFrom");

                    b.HasIndex("branchIdTo");

                    b.HasIndex("warehouseIdFrom");

                    b.HasIndex("warehouseIdTo");

                    b.ToTable("TransferOrders");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOrderLine", b =>
                {
                    b.Property<string>("transferOrderLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("transferOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOrderId");

                    b.ToTable("TransferOrderLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOut", b =>
                {
                    b.Property<string>("transferOutId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchIdFrom")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchIdTo")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("transferOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("transferOutNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("warehouseIdFrom")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("warehouseIdTo")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("transferOutId");

                    b.HasIndex("branchIdFrom");

                    b.HasIndex("branchIdTo");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseIdFrom");

                    b.HasIndex("warehouseIdTo");

                    b.ToTable("TransferOuts");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOutLine", b =>
                {
                    b.Property<string>("transferOutLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<float>("qty")
                        .HasColumnType("real");

                    b.Property<float>("qtyInventory")
                        .HasColumnType("real");

                    b.Property<string>("transferOutId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.HasKey("transferOutLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOutId");

                    b.ToTable("TransferOutLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Vendor", b =>
                {
                    b.Property<string>("vendorId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("HasChild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vendorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("vendorId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            vendorId = "00000000-0000-0000-0000-000000000001",
                            HasChild = "No",
                            city = "Hanoi",
                            country = "VN",
                            createdAt = new DateTime(2025, 11, 1, 7, 51, 0, 853, DateTimeKind.Utc).AddTicks(8557),
                            description = "Default vendor",
                            province = "HN",
                            size = 1,
                            street1 = "12 Supplier Rd",
                            street2 = "",
                            vendorName = "Acme Supplier"
                        });
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.VendorLine", b =>
                {
                    b.Property<string>("vendorLineId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("fax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("mobilePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("officePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("personalEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("salutation")
                        .HasColumnType("int");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("workEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("vendorLineId");

                    b.HasIndex("vendorId");

                    b.ToTable("VendorLines");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Warehouse", b =>
                {
                    b.Property<string>("warehouseId")
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("nvarchar(38)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("street2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("warehouseId");

                    b.HasIndex("branchId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            warehouseId = "00000000-0000-0000-0000-000000000001",
                            branchId = "00000000-0000-0000-0000-000000000001",
                            city = "Hanoi",
                            country = "VN",
                            createdAt = new DateTime(2025, 11, 1, 7, 51, 0, 853, DateTimeKind.Utc).AddTicks(8523),
                            description = "Main warehouse",
                            province = "HN",
                            street1 = "Zone A",
                            street2 = "",
                            warehouseName = "Central WH"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NetCore_Update.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NetCore_Update.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NetCore_Update.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.CustomerLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Customer", "customer")
                        .WithMany("customerLine")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.PurchaseOrder", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany("purchaseOrderLine")
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("purchaseOrder");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Receiving", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany()
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("purchaseOrder");

                    b.Navigation("vendor");

                    b.Navigation("warehouse");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.ReceivingLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Receiving", "receiving")
                        .WithMany()
                        .HasForeignKey("receivingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Receiving", null)
                        .WithMany("receivingLine")
                        .HasForeignKey("receivingId1");

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("product");

                    b.Navigation("receiving");

                    b.Navigation("warehouse");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.SalesOrder", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.SalesOrderLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany("salesOrderLine")
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("salesOrder");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Shipment", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany()
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("customer");

                    b.Navigation("salesOrder");

                    b.Navigation("warehouse");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.ShipmentLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Shipment", "shipment")
                        .WithMany()
                        .HasForeignKey("shipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Shipment", null)
                        .WithMany("shipmentLine")
                        .HasForeignKey("shipmentId1");

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("product");

                    b.Navigation("shipment");

                    b.Navigation("warehouse");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferIn", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branchFrom");

                    b.Navigation("branchTo");

                    b.Navigation("transferOrder");

                    b.Navigation("warehouseFrom");

                    b.Navigation("warehouseTo");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferInLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.TransferIn", "transferIn")
                        .WithMany("transferInLine")
                        .HasForeignKey("transferInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("transferIn");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOrder", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branchFrom");

                    b.Navigation("branchTo");

                    b.Navigation("warehouseFrom");

                    b.Navigation("warehouseTo");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOrderLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany("transferOrderLine")
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("transferOrder");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOut", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("branchFrom");

                    b.Navigation("branchTo");

                    b.Navigation("transferOrder");

                    b.Navigation("warehouseFrom");

                    b.Navigation("warehouseTo");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOutLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCore_Update.Models.Invent.TransferOut", "transferOut")
                        .WithMany("transferOutLine")
                        .HasForeignKey("transferOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("transferOut");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.VendorLine", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Vendor", "vendor")
                        .WithMany("vendorLine")
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Warehouse", b =>
                {
                    b.HasOne("NetCore_Update.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Customer", b =>
                {
                    b.Navigation("customerLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.PurchaseOrder", b =>
                {
                    b.Navigation("purchaseOrderLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Receiving", b =>
                {
                    b.Navigation("receivingLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.SalesOrder", b =>
                {
                    b.Navigation("salesOrderLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Shipment", b =>
                {
                    b.Navigation("shipmentLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferIn", b =>
                {
                    b.Navigation("transferInLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOrder", b =>
                {
                    b.Navigation("transferOrderLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.TransferOut", b =>
                {
                    b.Navigation("transferOutLine");
                });

            modelBuilder.Entity("NetCore_Update.Models.Invent.Vendor", b =>
                {
                    b.Navigation("vendorLine");
                });
#pragma warning restore 612, 618
        }
    }
}
